excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://juanmirod.github.io
title: "Por amor al código" 
tagline: "Code snippeds y reflexiones sobre tecnología"
description: "juanmirod.github.io"
paginate: 1
