excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://blog.juanmirodriguez.es
title: "Por amor al código" 
tagline: "Code snippeds y reflexiones sobre tecnología"
description: "Blog de juanmirodriguez.es"
paginate: 1
